Messenger\Domain\Model\Event\PublishedMessage:
  type: entity
  table: event_published_message_tracker
  repositoryClass: Messenger\Infrastructure\Application\Notification\DoctrinePublishedMessageTracker
  id:
    trackerId:
      column: tracker_id
      type: integer
      generator:
        strategy: AUTO
  fields:
    mostRecentPublishedMessageId:
      column: most_recent_published_message_id
      type: bigint
    exchangeName:
      type: string
      column: exchange_name

